[package]
name = "nextchat-server"
version = "0.1.0"
authors = ["NextChat contributors"]
edition = "2018"

[dependencies]
actix = "0.10"
actix-web = "3"
actix-web-actors = "3"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99.11"
dotenv = "0.15"
rust-argon2 = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
sqlx = { version = "0.4.2", features = ["chrono", "postgres", "runtime-actix-rustls", "uuid"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
